# Generated by Django 4.2.1 on 2023-06-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='users/')),
            ],
        ),
    ]
